### ISSUE TITLE
Залипающие спрайты газа. Скраббер.

### ISSUE THREAD

**Issue by sovok4** [TauCetiStation/RuBaystation12#52]
Собственно, когда набегали гриферы в четверг, после устранения аварий осталось следующее http://prntscr.com/86s63n

Переносной скраббер фильтрует вредные газы до какого-то малого, но все ещё опасного значения. Затем перестает фильтровать вовсе.

**Comment by volas** [comment]
Не относится к проблемам кириллицы, не тот трекер.
